# Code generated by the fine-tuned code llama instruct
@always_inline
fn _sum(a: Int, b: Int) -> Int:
    return a + b

    fn _sum(a: Int, b: Int) -> Int:
        return a + b

# Comment and Code bellow were added in order to easily test the generated code above
    #return _sum

fn main():
    print(_sum(1, 2))