# Code snippet generated by context
fn sum(a: Int, b: Int) -> Int {
    return a + b;
}

# Code snippet generated by ChatGPT (GPT-4) on few-shot learning
@always_inline
fn sum(a: Int, b: Int) -> Int:
    return a + b


