# Generated by ChatGPT (GPT-4) based on 6 examples provided of Mojo code
@always_inline
fn difference[T: element_trait](set1: Set[T], set2: Set[T]) -> Set[T]:
    var result = Set[T]()
    for element in set1:
        if element not in set2:
            result.add(element)
    return result
